

#ifndef _GAME_SIMULATION_STRUCTS_H_
#define _GAME_SIMULATION_STRUCTS_H_

#define _GAMESIM_MODE_NO_COMMAND 0

#define _GAMESIM_MODE_MOVE_CELL_UP 1
#define _GAMESIM_MODE_MOVE_CELL_DOWN 2
#define _GAMESIM_MODE_MOVE_CELL_LEFT 3
#define _GAMESIM_MODE_MOVE_CELL_RIGHT 4

#define _GAMESIM_MODE_CELL_ENTER 5
#define _GAMESIM_MODE_CELL_RESET 6


#define _GSIM_ARR_SIZE_X 5
#define _GSIM_ARR_SIZE_Y 5

#define _GSIM_ARR_SIZE_NOT_SET -1


#endif // !_GAME_SIMULATION_STRUCTS_H_
